### ISSUE TITLE
Partial String Lights Up

### ISSUE THREAD

**Issue by Kosh42** [FalconChristmas/fpp-HomeAssistant#2]
Seems to be working well (many thanks). 

But when I turn the light on and set the colour in Home Assistant, only the first 100 pixels (I'm guessing, didn't count them) light up, with the remainder of the string staying dark. 

When I test the string in FPP, or play a sequence in FPP, the whole string works as expected, so not a set-up issue from that front I think.

**Comment by cpinkham** [comment]
Make sure your model covers your whole string.  The plugin just uses FPP's built-in FPP Commands to turn the model on and fill it with a color, so if the model is configured correctly (testable via the Channel Tester page), then all pixels should light up when HA tells them to light.

**Comment by cpinkham** [comment]
Closing ticket, if anything, this is a FPP issue since a FPP Command is used to fill the model with the specified color.
