### ISSUE TITLE
FPP Sensors missing from UI on FPP 7.1

### ISSUE THREAD

**Issue by kevinsaucier** [FalconChristmas/fpp-HomeAssistant#20]
# Please answer the following:
**FPP Version and Hardware**: 

FPP 7.1 running on multiple Kulp controllers

**Describe the bug**

In the Home Assistant plugin page, the temp and VIN sensors do not show up in the UI so there is no way to enable/configure those sensors.

Reproduce:

Load the plugin, restart/reboot FPP, access the HA plugin page and the overlays/GPIO are listed but the cape sensors are not.

**Comment by dkulp** [comment]
Fixed
