### ISSUE TITLE
Feature Request - Support WLED effects as HA light effects

### ISSUE THREAD

**Issue by ravenridgelights-turtle** [FalconChristmas/fpp-HomeAssistant#4]
I would love to see the effects that Dan added to FPP with WLED .. to be able to be added to each device "entity" . 
I know its all beta and a start but i think it would add greatness to lots of ppl

thanks for reading 
love the ha plugin

**Comment by ravenridgelights-turtle** [comment]
or even fpp commands from home assistant would be great 
through each light card

**Comment by MagicMountainMan** [comment]
I second this. Calling WLED effects from Home Assistant in a cleaner and easier way then sending commands would be really slick.

**Comment by cpinkham** [comment]
I am testing a patch for this.  The patch will allow the plugin user to configure FPP Commands to run WLED effects on the model.  The FPP Commands will be treated by HA as light effects allowing the user to trigger the WLED effects via the HA UI.
