### ISSUE TITLE
Feature Request - Expose additional information via sensors

### ISSUE THREAD

**Issue by brianbarrell** [FalconChristmas/fpp-HomeAssistant#5]
I would like to see more sensors being reported.  Like CPU Temperature and FPP IP Address and percentage of space remaing on SD card.  Thanks

**Comment by cpinkham** [comment]
I think this is best implemented on the FPP side, not in the plugin itself.  The HA plugin already has the ability to expose all FPP sensors to HA including CPU temperature.  If a "disk utilization" sensor is added to FPP, it would automatically appear in the HA plugin UI and also allow the user to choose to display that utilization in the FPP UI header as well.  I created a ticket on the FPP side to add a disk utilization sensor.  It also might be good for us to expose all sensors via MQTT anyway.  If so, the main benefit of the HA plugin sensor support would be auto discovery, but any MQTT subscriber could take advantage of the sensors.
