### ISSUE TITLE
Plugin Sending Messages to Wrong Topic

### ISSUE THREAD

**Issue by dramamoose** [FalconChristmas/fpp-HomeAssistant#6]
I have FPP and HomeAssistant (and Zigbee and Zwave and Yi etc) configured to utilize the homeassistant topic on my server. However, rather than publishing to /homeassistant/light, this plugin appears instead to be publishing to /homeassistant/falcon/player/ha/light

Am I missing a configuration setting somewhere? I was really hoping this would be a good option for controlling my house-mounted lights when I'm not running a show.

**Comment by bbene** [comment]
Seeing the same thing here. I wonder if this is a change related to the 5.x branches of FPP. I'm seeing the above behavior on both 5.0 and 5.1.

**Comment by cpinkham** [comment]
The command and state topics are user defined, so FPP does use its own path for those topics.  The Home Assistant auto-config topics are HA defined and FPP uses /homeassistant/light for those.  Here is an example from one of my systems:

homeassistant/light/rpi5/String-00/config {"brightness":true,"command_topic":"falcon/player/rpi5/ha/light/String-00/cmd","effect":false,"name":"String-00","qos":0,"rgb":true,"schema":"json","state_topic":"falcon/player/rpi5/ha/light/String-00/state"}

For the above light, FPP also sends out a message on another topic "falcon/player/rpi5/ha/light/String-00/config", but you can ignore that, HA doesn't use it.  it is for FPP internal use only.
