### ISSUE TITLE
Setup Instructions

### ISSUE THREAD

**Issue by techguydave** [FalconChristmas/fpp-HomeAssistant#8]
There don't appear to be any instructions on how to set this up.

**Comment by artem82** [comment]
please any instructions

**Comment by cpinkham** [comment]
Install the plugin, select some models, optionally name them in FPP, restart fppd, and they should be discoverable in Home Assistant.  Do you have any experience with Home Assistant MQTT discovery?

**Comment by cpinkham** [comment]
Closing ticket.  The FPP side of things is pretty automatic and simple.  There is a little help on the popup 'F1' help page for the plugin.  I will add some more notes as I add more features.
