### ISSUE TITLE
Stops FPPD and will not restart

### ISSUE THREAD

**Issue by Mark79864** [FalconChristmas/fpp-HomeAssistant#9]
FPP 5.3
Raspberry Pi 4 2GB.

Installing Home assistant plugin prompts for restart of FPPD.
FPPD then stops and will not start again (even after full reboot of the Pi).

Steps taken:
1. Stopped anything playing.
2. Added HA plugin.
3. Ticked 'CPU' sensor only (no GPIO or models).
4. Prompt by FPP to restart FPPD. Clicked restart.
No errors given by FPP as to FPPD not restarting. It gives notification it has started. Red banner saying FPPD is stopped continues to show.

![image](https://user-images.githubusercontent.com/72605347/142575292-abb3a0f8-7677-4c23-8a98-8fea5a6ed8dc.png)
![image](https://user-images.githubusercontent.com/72605347/142575261-54d4506d-083b-46da-8120-0860f377f7c3.png)

My Home Assistant instance has also not found it.

Uninstalling the plugin resolves FPPD not starting issue.

My first guess is an issue with HA plugin requiring more to be downloaded when I hit 'restart fppd' in the banner.

**Comment by Mark79864** [comment]
Error log from FPPD.log:
`2021-11-19 19:06:38.158 (1778) [General] /opt/fpp/src/fppd.cpp:518: Creation of Scheduler, Playlist, and Sequence Complete
2021-11-19 19:06:38.233 (1778) [Plugin] src/FPP-HomeAssistant.cpp:22: Initializing Home Assistant Plugin
2021-11-19 19:06:38.234 (1778) [General] /opt/fpp/src/common.cpp:665: JSON File /home/fpp/media/config/gpio.json does not exist
2021-11-19 19:06:38.234 (1778) [General] /opt/fpp/src/fppd.cpp:226: Crash handler called:  11`
Looks to be that gpio.json does not exist anymore.

**Comment by camrun91** [comment]
@Mark79864 I am having this same issue as well.

**Comment by kevinbegley** [comment]
Same here

**Comment by ledshows** [comment]
Same Issue Here.

2022-01-11 12:26:04.633 (1320) [General] /opt/fpp/src/common.cpp:665: JSON File /home/fpp/media/config/gpio.json does not exist
2022-01-11 12:26:04.634 (1320) [General] /opt/fpp/src/fppd.cpp:226: Crash handler called:  11
2022-01-11 12:26:09.863 (1320) [General] /opt/fpp/src/fppd.cpp:210: Stack: 
[New LWP 1340]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/arm-linux-gnueabihf/libthread_db.so.1".
__waitpid (options=0, stat_loc=0xbee60e8c, pid=1354) at ../sysdeps/unix/sysv/linux/waitpid.c:30
30	../sysdeps/unix/sysv/linux/waitpid.c: No such file or directory.

**Comment by Oxfordjon** [comment]
Same issue here

**Comment by cpinkham** [comment]
Is anyone still having this issue?  If so, can you let me know what version of FPP you are on and if you have updated the HA plugin to the latest version via the FPP Plugin Manager?  I tested FPP v6 with the latest plugin version and can not reproduce this issue.  The gpio.json log entry should be unrelated, it is a warning, not an error.  The HA plugin tries to open the file but it can't be found.  That shouldn't cause an issue with the plugin running.

**Comment by Mark79864** [comment]
> Is anyone still having this issue? If so, can you let me know what version of FPP you are on and if you have updated the HA plugin to the latest version via the FPP Plugin Manager? I tested FPP v6 with the latest plugin version and can not reproduce this issue. The gpio.json log entry should be unrelated, it is a warning, not an error. The HA plugin tries to open the file but it can't be found. That shouldn't cause an issue with the plugin running.

I'll pull out my Pi and try again. I haven't tried since when I posted this.

**Comment by camrun91** [comment]
I found my issues was a configuration issue.

**Comment by edalquist** [comment]
This may be an issue with configuring the HA plugin without configuring MQTT in FPP. If that happens the plugin tries to dereference the mqtt object which is null.

**Comment by cpinkham** [comment]
I believe this is fixed now by 8a827cc

If MQTT is not configured or is not connected then the plugin won't be initialized and therefore won't try to reference the mqtt instance.  If the problem reoccurs, the ticket can be reopened.
